servers:
  - url: "{scheme}://{host}{basePath}"
    variables:
      scheme:
        default: https
      host:
        default: api.browserstack.com
      basePath:
        default: "/5"
  - url: "{scheme}://{host}"
    variables:
      scheme:
        default: https
      host:
        default: api-cloud.browserstack.com

openapi: 3.0.2
info:
  title: BrowserStack Local Testing
  version: 5.0.0
  description: BrowserStack Local Testing API
  license:
    name: MIT License
    url: https://opensource.org/license/mit/

externalDocs:
  description: Find out more about BrowserStack
  url: https://www.browserstack.com/docs/


security:
  - basicAuth: []

paths:
  /local/v1/list:
    get:
      tags:
      - LocalTesting
      summary: Fetches list of recent binary instances
      description: Fetches list of recent binary instances for local testing. Note that
        the binary should have been started with the --enable-logging-for-api parameter.
      operationId: getLocalBinaryInstances
      x-cli-section: "Instances"
      x-cli-display: [id, localIdentifier, startTime, hostname]
      parameters:
      - name: auth_token
        in: query
        required: true
        schema:
          type: string
          description: Your BrowserStack access token
          example: ACCESS_TOKEN
      - name: last
        in: query
        schema:
          type: number
          description: 'The number of recent binary instances to be listed. Maximum
            value: 100. Default value: 20.'
          default: 20
      - name: state
        in: query
        schema:
          type: string
          description: 'Filter binary instances by state. Accepted values: running,
            all. Default value: running.'
          enum:
          - running
          - all
          default: running
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                title: GetLocalBinaryInstancesResponse
                type: object
                required:
                - api_version
                - meta_data
                - instances
                properties:
                  api_version:
                    type: string
                    description: API version
                    example: v1
                  meta_data:
                    type: object
                    description: Metadata
                    properties:
                      params:
                        type: object
                        description: Parameters
                        additionalProperties: true
                    additionalProperties: true
                  instances:
                    type: array
                    items:
                      $ref: '#/components/schemas/LocalBinaryInstance'
        '400':
          $ref: '#/components/schemas/400.BadRequest'
        '401':
          $ref: '#/components/schemas/401.Unauthorized'
        '404':
          $ref: '#/components/schemas/404.NotFound'
        '422':
          $ref: '#/components/schemas/422.UnprocessableEntity'
        '500':
          $ref: '#/components/schemas/5xx.InternalServerError'
  /local/v1/{localInstanceId}:
    get:
      tags:
      - LocalTesting
      summary: Fetches details of a Local binary instance
      description: Fetches details of a Local binary instance used for local testing.
        Note that the binary should have been started with the --enable-logging-for-api
        parameter.
      operationId: getLocalBinaryInstance
      x-cli-section: "Instances"
      parameters:
      - name: localInstanceId
        in: path
        required: true
        schema:
          type: string
          description: The local instance ID
          example: QUERTY1
      - name: auth_token
        in: query
        required: true
        schema:
          type: string
          description: Your BrowserStack access token
          example: ACCESS_TOKEN
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                title: GetLocalBinaryInstanceResponse
                type: object
                required:
                - api_version
                - meta_data
                - instances
                properties:
                  api_version:
                    type: string
                    description: API version
                    example: v1
                  meta_data:
                    type: object
                    description: Metadata
                    properties:
                      params:
                        type: object
                        description: Parameters
                        additionalProperties: true
                    additionalProperties: true
                  instances:
                    type: array
                    items:
                      $ref: '#/components/schemas/LocalBinaryInstance'
        '400':
          $ref: '#/components/schemas/400.BadRequest'
        '401':
          $ref: '#/components/schemas/401.Unauthorized'
        '404':
          $ref: '#/components/schemas/404.NotFound'
        '422':
          $ref: '#/components/schemas/422.UnprocessableEntity'
        '500':
          $ref: '#/components/schemas/5xx.InternalServerError'
    delete:
      tags:
      - LocalTesting
      summary: Disconnect a Local binary instance
      description: Disconnect a Local binary instance
      operationId: disconnectLocalBinaryInstance
      x-cli-section: "Instances"
      parameters:
      - name: localInstanceId
        in: path
        required: true
        schema:
          type: string
          description: The local instance ID
          example: QUERTY1
      - name: auth_token
        in: query
        required: true
        schema:
          type: string
          description: Your BrowserStack access token
          example: ACCESS_TOKEN
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                title: DisconnectLocalBinaryInstanceResponse
                type: object
                required:
                - api_version
                - meta_data
                - message
                properties:
                  api_version:
                    type: string
                    description: API version
                    example: v1
                  meta_data:
                    type: object
                    description: Metadata
                    properties:
                      params:
                        type: object
                        description: Parameters
                        additionalProperties: true
                    additionalProperties: true
                  message:
                    type: string
                    description: QUERTY1 successfully disconnected
        '400':
          $ref: '#/components/schemas/400.BadRequest'
        '401':
          $ref: '#/components/schemas/401.Unauthorized'
        '404':
          $ref: '#/components/schemas/404.NotFound'
        '422':
          $ref: '#/components/schemas/422.UnprocessableEntity'
        '500':
          $ref: '#/components/schemas/5xx.InternalServerError'

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

  schemas:
    400.BadRequest:
      description: Bad request.
    401.Unauthorized:
      description: Your BrowserStack access credentials are invalid.
    403.Forbidden:
      description: Authorized user is not the owner of the resource.
    404.NotFound:
      description: The requested resource could not be found.
    422.UnprocessableEntity:
      description: Request is well-formed but has semantic errors. The response will provide
        more details about error.
    5xx.InternalServerError:
      description: Indicates an error with BrowserStack servers.
    Browser:
      title: Browser
      type: object
      required:
      - browser
      - browser_version
      properties:
        browser:
          type: string
          example: Chrome
        browser_version:
          type: string
          example: '80.0'
    BrowserDevice:
      title: BrowserDevice
      allOf:
      - $ref: '#/components/schemas/Browser'
      - type: object
        required:
        - devices
        - real_devices
        properties:
          browser:
            type: string
            example: Android Browser
          devices:
            type: array
            items:
              type: string
              example: Google Nexus
          real_devices:
            type: array
            items:
              type: string
            maxItems: 0
    BrowserList:
      title: BrowserList
      type: array
      items:
        $ref: '#/components/schemas/BrowserPlatform'
    BrowserPlatform:
      title: BrowserPlatform
      allOf:
      - $ref: '#/components/schemas/Browser'
      - type: object
        required:
        - os
        - os_version
        properties:
          os:
            type: string
            example: Windows
          os_version:
            type: string
            example: '10'
          device:
            type: string
            example:
          real_mobile:
            type: boolean
            example:
    BrowserRealDevice:
      title: BrowserRealDevice
      allOf:
      - $ref: '#/components/schemas/Browser'
      - type: object
        required:
        - devices
        - real_devices
        properties:
          browser:
            type: string
            example: Android Browser
          devices:
            type: array
            items:
              type: string
            maxItems: 0
          real_devices:
            type: array
            items:
              type: string
              example: Google Pixel 6 Pro
    LocalBinaryInstance:
      title: LocalBinaryInstance
      type: object
      required:
      - id
      - email
      - lastActiveOn
      - startTime
      - localIdentifier
      properties:
        id:
          type: string
          description: Unique identifier for the Local instance.
          example: QUERTY1
        email:
          type: string
          description: User account that started the Local instance.
          example: john@browserstack.com
        hostname:
          type: string
          description: Hostname for the machine running the Local instance.
          example: my-local-box
        lastActiveOn:
          type: string
          description: Timestamp at which the Local instance was last active.
          example: 2013-03-14 16:25:45 UTC
        startTime:
          type: string
          description: Timestamp at which the Local instance was started.
          example: 2013-03-14 16:25:45 UTC
        endTime:
          type: string
          description: Timestamp at which the Local instance was terminated.
          example: 2013-03-14 16:25:45 UTC
        disconnectReason:
          type: string
          description: Reason for termination of the Local instance.
          example: User terminated the instance.
        commandLineParams:
          type: string
          description: Command line parameters used to start the Local instance.
          example: --key <access_key> --enable-logging-for-api --local-identifier <local_identifier>
        localIdentifier:
          type: string
          description: Identifier for the Local instance.
          example: 4207442b2b0567368956dba064c22a3235a76214
        public-IP:
          type: string
          description: Public IP address of the machine running the Local instance.
          example: 8.8.4.4
        privateIP:
          type: array
          items:
            type: string
            description: Private IP address of the machine running the Local instance.
          example:
          - 127.0.0.1
          - 10.100.100.1
    NewWorker:
      title: NewWorker
      allOf:
      - type: object
        required:
        - url
        - os
        - os_version
        properties:
          url:
            type: string
            description: URL to be opened in the browser
            example: https://www.google.com/ncr
          timeout:
            type: number
            description: 'Time in seconds before the worker is terminated. The default
              value is 300 seconds and the minimum value is 60 seconds. IMPORTANT: Irrespective
              of the timeout parameter, a browser worker is alive for a maximum time of
              1800 seconds.'
            example: 300
          os:
            type: string
            description: Operating system name.
            example: Windows
          os_version:
            type: string
            description: Operating system version.
            example: '10'
          name:
            type: string
            description: Name of the worker.
            example: qunit-test-pricing
          build:
            type: string
            description: Name of the build the session is running under.
            example: staging-build
          project:
            type: string
            description: Name of the project the build is organized under.
            example: pricing-project
          browserstack.video:
            type: boolean
            description: Enable video recording for the session. The default value is
              false.
            example: true
          resolution:
            type: string
            description: Set the resolution of VM before the beginning of your test. Available
              for Desktop only. The default value is 1024x768.
            example: 1024x768
      - oneOf:
        - type: object
          required:
          - browser
          - browser_version
          properties:
            browser:
              type: string
              description: Browser name.
              example: Chrome
            browser_version:
              type: string
              description: Browser version.
              example: '80.0'
        - type: object
          properties:
            device:
              type: string
              description: Device name. If a device is not provided it defaults to the
                first device available for that os version.
              example: iPhone 11 Pro
            browser:
              type: string
              description: Browser name.
              example: Chrome
            browser_version:
              type: string
              description: Browser version.
              example: '80.0'
    Status:
      title: Status
      type: object
      required:
      - used_time
      - running_sessions
      - session_limit
      - total_available_time
      properties:
        used_time:
          type: number
          example: 10
        running_sessions:
          type: number
          example: 0
        session_limit:
          type: number
          example: 0
        total_available_time:
          type: string
          example: Unlimited Testing Time
    Worker:
      title: Worker
      allOf:
      - $ref: '#/components/schemas/BrowserPlatform'
      - type: object
        required:
        - id
        properties:
          id:
            type: number
            description: ID of the worker.
            example: 122326697
          sessionId:
            type: string
            description: ID of the session.
            example: 550709149fe79e949363b581e774d5ebffa1b8fe
          status:
            type: string
            enum:
            - queue
            - running
            description: Current status of the worker.
            example: running
          browser_url:
            type: string
            description: Dashboard URL of the session
            example: ''
