name: npm test
on:
  push:
    branches: [main]

env:
  VITE_BROWSERSTACK_USERNAME: "${{ secrets.VITE_BROWSERSTACK_USERNAME }}"
  VITE_BROWSERSTACK_KEY: "${{ secrets.VITE_BROWSERSTACK_KEY }}"

jobs:
  test-node-lts:
    name: "node.js lts"
    runs-on: ubuntu-latest
    environment: BrowserStackEnv
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "lts"
          cache: "npm"

      - name: Build
        run: |
          npm install
          npm run build
          npm test


  test-node-v18:
    name: "node.js v18"
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [test-node-lts]
    environment: BrowserStackEnv
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Build
        run: |
          npm install
          npm run build
          npm test
