name: Publish npm package

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Confirm publish by typing "publish"'
        required: true
      tag:
        description: 'NPM tag'
        required: true
        default: 'latest'

concurrency:
  group: publish-npm-package
  cancel-in-progress: false

env:
  VITE_BROWSERSTACK_USERNAME: "${{ secrets.VITE_BROWSERSTACK_USERNAME }}"
  VITE_BROWSERSTACK_KEY: "${{ secrets.VITE_BROWSERSTACK_KEY }}"
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  publish-node-lts:
    name: "node.js lts"
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && (github.event_name == 'release' || github.event.inputs.confirm == 'publish')
    environment: BrowserStackEnv
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: pnpm/action-setup@5280c022466e8e5ea34ea201e2fda33875aeefdb # v6

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: "lts/*"
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build and test
        run: pnpm build:types && pnpm build && echo "Skipping tests during publish phase as they are verified in CI."

      - name: npm publish
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            TAG="latest"
            if [ "${{ github.event.release.prerelease }}" = "true" ]; then
              TAG="next"
            fi
          else
            TAG="${{ github.event.inputs.tag }}"
          fi
          pnpm publish -r --tag $TAG --no-git-checks
        env:
          NODE_AUTH_TOKEN: "${{ secrets.NPM_PUBLISH_TOKEN }}"
